### PR TITLE
Si4463 testing board

### LINKED ISSUE #130: Create Si4463 Integration Testing Board
Due to the form factor of the COTS breakout for the Si4463 that was ordered, an additional PCB will be required to connect the breakout to a Teensy and antenna. This board should provide connections from the all available pins on the breakout to the corresponding Teensy pins, and contain a 50 ohm impedance matched trace to connect to a side mounted SMA. Ideally this board will also be able to fit in an L1 for testing, so its shortest dimension should be <2.5 inches, including the antenna. 

This issue is high priority since the boards need to arrive, be soldered, and get tested before the October launch.

### PR DESCRIPTION
**Pull request by jhauerst**
This adds the PCB to mount the RF4463F30 to for RSSI data collection flight tests, as well as the nosecone design that should fit the board. The PCB should be ordered as soon as possible after the design is reviewed, so it can arrive in time for the October flight test. 

Closes #130

### CODE REVIEW

**Review by dshi0322 — COMMENTED** [review]
In the meeting I remember you said that the blue traces couldnt get more seperation. I forgot cause what was the reason again? They are kinda close for quite some distance and cross talk / coupling could happen.

**Comment by jhauerst** [comment]
> In the meeting I remember you said that the blue traces couldnt get more seperation. I forgot cause what was the reason again? They are kinda close for quite some distance and cross talk / coupling could happen.



> In the meeting I remember you said that the blue traces couldnt get more seperation. I forgot cause what was the reason again? They are kinda close for quite some distance and cross talk / coupling could happen.

Which traces specifically?

**Comment by LShapir0** [comment]
> In the meeting I remember you said that the blue traces couldnt get more seperation. I forgot cause what was the reason again? They are kinda close for quite some distance and cross talk / coupling could happen.

I believe the reason for close distance is impedance matching .

**Comment by dshi0322** [comment]
> > In the meeting I remember you said that the blue traces couldnt get more seperation. I forgot cause what was the reason again? They are kinda close for quite some distance and cross talk / coupling could happen.
> 
> Which traces specifically?

Parallel blue traces on the left of teensy

**Comment by jhauerst** [comment]
> > > In the meeting I remember you said that the blue traces couldnt get more seperation. I forgot cause what was the reason again? They are kinda close for quite some distance and cross talk / coupling could happen.
> > 
> > 
> > Which traces specifically?
> 
> Parallel blue traces on the left of teensy

The board that's in there should be updated to not have those traces. Should look like this unless I somehow forgot to commit or push.
image

**Review by varun-un — APPROVED** [review]

**Pull request merged**
